language: ruby
branches:
  only:
  - master
rvm:
- 2.6.2
before_install:
  - gem update --system
  - gem install bundler
before_script:
 - chmod +x ./deploy
script: ./deploy
exclude: [vendor]
sudo: false
