title: KovuTheHusky
description: "A personal website for KovuTheHusky."
permalink: /post/:year/:month/:day/:title
hostname: "kovu.dog"

defaults:
  -
    scope:
      path: "node_modules/**"
    values:
      sitemap: false

include: 
  - .nojekyll
  - _icons
  - node_modules

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-file-size
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  load_paths:
    - _sass
    - node_modules
