title: KovuTheHusky
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: /post/:year/:month/:day/:title
baseurl: "/kovuthehusky.com"
url: "https://kovuthehusky.com"
twitter_username: kovuthehusky
github_username: kovuthehusky

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass
    - node_modules
include: [.nojekyll, _icons]
exclude: [vendor]
