title: KovuTheHusky
description: "A personal website for KovuTheHusky."
permalink: /post/:year/:month/:day/:title
hostname: "kovu.dog"

defaults:
  -
    scope:
      path: "node_modules/**"
    values:
      sitemap: false

include: 
  - .nojekyll

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-file-size
  - jekyll-node-module
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

node_modules:
  modules_dir: node_modules
  copy:
  - source: .
    target: node_modules

sass:
  load_paths:
    - _sass
    - node_modules
