title: KovuTheHusky
description: "A personal website for KovuTheHusky."
permalink: /post/:year/:month/:day/:title
baseurl: ""
url: "https://kovuthehusky.com"
twitter_username: kovuthehusky
github_username: kovuthehusky

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass
    - node_modules
include: 
  - .nojekyll
  - _icons
  - node_modules
