name: Build and deploy Jekyll site to GitHub Pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Gem install bundler
        id: gem-install-bundler
        run: gem install bundler

      - run: bundle install

      - name: Jekyll build
        uses: helaili/jekyll-action@2.0.5
        with:
          build_only: true
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}

      - name: Pokemon GO
        id: pokemon-go
        run: ruby pokemongo.rb

      - name: Projects
        id: projects
        run: curl -X GET "https://status.kovuthehusky.com/projects.json" > _data/projects.json

      - name: Jekyll deploy
        uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
